### ISSUE TITLE
Logging to stdout doesn't seem to work for isolated workers

### ISSUE THREAD

**Issue by das-nagnag** [Flowpack/jobqueue-common#63] opened 2024-06-12 09:05 UTC
We’re currently attempting to replace our loggers to log on stdout instead of writing logs to bigquery (for obvious reasons). We’re running a flow 7.3 project (`flowpack/jobqueue-common` is running @3.3.0) and have two pods in parallel in our deployment: a “normal” application pod and a worker pod that runs php /app/flow job:work --verbose on a particular queue. Now we have the “issue” that most of the processes in our application are being executed as jobs inside this queue. And we can’t seem to get any logs from jobs in this queue, at least not to stdout. The bigquery logs seem to have worked in the past.

After a [short but helpful conversation](https://neos-project.slack.com/archives/C04V4C6B0/p1718178598163579) with @kitsunet I was able to identify that the cause of this seems to be the fact that our workers are running with `executeIsolated: true`. Jobs/workers running in this mode don't seem to correctly redirect their "internal" stdout to the "parent system's" stdout. 

So far I don't seem to be able to identify the exact location of the issue, where things go wrong. Also I can't justify to invest more time into this issue from my job's point of view. However, if someone could point me to the root of the issue, I might be able to (attempt) to fix the issue in my own time after work.

**Comment by bwaidelich** [comment] 2024-06-12 09:15
Thanks for reporting.

I think you already pinned down the root cause. It is in these lines (basically):
https://github.com/Flowpack/jobqueue-common/blob/2db88c20fc3cb8b5fe7a02bf5aaa50e4f732e6ec/Classes/Job/JobManager.php#L123-L126

This just uses our nasty `Scripts::executeCommand()` construct to trigger the jobs.
Instead we should use a more sophisticated sub request mechanism such that we can communicate between worker and manager threads.

I once created a [symfony process](https://symfony.com/doc/current/components/process.html) abstraction for Flow ( https://github.com/bwaidelich/Wwwision.BatchProcessing/blob/main/Classes/BatchProcess.php).
Maybe something like that could work more reliably

**Comment by bwaidelich** [comment] 2024-06-12 09:16
> We’re currently attempting to replace our loggers to log on stdout instead of writing logs to bigquery (for obvious reasons)

what are the obvious reasons? :)

**Comment by das-nagnag** [comment] 2024-06-12 09:50
> > We’re currently attempting to replace our loggers to log on stdout instead of writing logs to bigquery (for obvious reasons)
> 
> what are the obvious reasons? :)

First of all the pricing, to my knowledge. We don't run any ETL processes on the logs that are in bigquery so there's no use to have it there in a data warehouse, really. Having the logs only in bigquery also makes looking for stuff a little more difficult in my experience (and that of my colleagues), as opposed to, for example, Google's LogExplorer which does also support JSON formatting of the logs (and/or their additional data) etc. Additionally we're trying to progress to more or less actual twelve-factor (web) apps that are, ideally, cloud native. Therefore logging directly to stdout (and the logs therefore also being available in the LogExplorer) seems to suggest itself a bit more than writing logs to BQ and paying for writing, reading and storing the logs there.

**Comment by das-nagnag** [comment] 2024-07-12 13:24
I finally had a bit of time to fiddle around with this a little. In the progress I realised that just turning the bool flag for `outputResults` in https://github.com/Flowpack/jobqueue-common/blob/2db88c20fc3cb8b5fe7a02bf5aaa50e4f732e6ec/Classes/Job/JobManager.php#L126 (third parameter) to `true` makes all the change and with this it already does put the job's output on stdout. I thought I had tried this already by changing the respective file in the running container and flushing the cache, but it still must've been stuck somewhere in cache.

Either way, my question to you @bwaidelich: Would you be opposed to a middle-ground solution where I don't fully rework the `Scripts::executeCommand`-bit and instead make a PR that turns the third parameter for `outputResults` into a variable configurable in the settings?

**Comment by bwaidelich** [comment] 2024-07-12 14:51
> Would you be opposed to a middle-ground solution  [...] a PR that turns the third parameter for outputResults into a variable configurable in the settings?

I don't fully understand your suggested solution. A PR for this package that adds some query option? or a PR to the `neos/flow` core that tweaks `Scripts::executeCommand`?

**Comment by das-nagnag** [comment] 2024-07-15 08:16
> I don't fully understand your suggested solution. A PR for this package that adds some query option? or a PR to the `neos/flow` core that tweaks `Scripts::executeCommand`?

Hi Bastian! My idea was a (more or less rudimentary) PR in this package here – I went ahead and made it as simple as I think might work: https://github.com/Flowpack/jobqueue-common/pull/65. This way the third parameter that is being passed to `Scripts::executeCommand`, which was hard-coded to `false`, would be configurable through the Settings (if needed, default is still `false`) and can be turned on by setting that value in the settings to `true`. 

Please excuse the slightly chaotic commits in that PR. Maybe a squash merge would be best for that, if that isn't standard anyway.

**Comment by das-nagnag** [comment] 2024-07-16 07:55
Thank you for fixing my PR yesterday! Are you planning on creating a new release? :) Otherwise I would have to require the main branch as dev branch which I don't think would be ideal

**Comment by bwaidelich** [comment] 2024-07-16 08:02
> Are you planning on creating a new release?

Yes, see https://github.com/Flowpack/jobqueue-common/pull/61#issuecomment-2228488459

**Comment by bwaidelich** [comment] 2024-07-16 08:10
It's released with https://github.com/Flowpack/jobqueue-common/releases/tag/3.4.0 now

@das-nagnag Thanks again for the contribution!

**Closed** 2024-07-16 08:10 UTC

**Comment by das-nagnag** [comment] 2024-07-16 09:17
Ah sorry, I didn't check that other PR :D Thank you so much for helping me with this! 🙌
